name: Themeing

on:
  push:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Install Flutter
      - uses: britannio/action-install-flutter@v1.1
        # with:
          # The channel/version of Flutter to be used e.g., beta or 2.0.0
          # version: # optional, default is stable
